### ISSUE TITLE
Feature: Add webserver using node.js/express and restructure code files

### ISSUE THREAD

**Issue by mehul-m-prajapati** [Manyap772/weather#10]
@Durgesh4993: 
 I will add webserver and REST APIs to fetch weather data

**Comment by mehul-m-prajapati** [comment]
- I will add webserver and REST APIs to fetch weather data

**Comment by Harshsahu11** [comment]
Yes , The data fetched from webserver will be appropriate. For its front end we can add some animations and some puzzle which will attract user to it.

**Comment by Harshsahu11** [comment]
I also want to be as a Contibutor in this Project.
