### ISSUE TITLE
[Feature] Add Sign Up and Login page 

### ISSUE THREAD

**Issue by ShreeluSantosh** [Manyap772/weather#15]
I've looked into your web application for weather-detecting in different locations. I think your project has great potential for help in weather-related applications, especially within the blockchain community. As the project is in early stages, I would like to help out by adding the following feature:

**Feature Name:** Sign Up and Login page
**Explanation:**

On checking out the website, there is a panel with at the top with different tiers of offerings for different prices. There's a Sign Up button for the free tier. On clicking this button though, nothing happens.

<img src="https://github.com/user-attachments/assets/10cad2f8-f73a-444a-97b9-a5637cddc39e" height="300"/>

I noticed that the repository is missing a page for Sign Up and Login. 

The functionality and user experience of the website would be greatly improved with the addition of signup/login page.

**Layout of the Signup/Login page:**
* two separate tabs for sign up and login
<img src="https://github.com/user-attachments/assets/8c3eff27-0135-48d9-8ce1-07c100116b2b" height="500" />
<img src="https://github.com/user-attachments/assets/ebe3b2ff-4a69-4fd7-b844-d19a14fad644" height="500" />

**Proposed Tech Stack:**
HTML, CSS, JavaScript

**Important Note:**
I'm a contributor in GirlScript Winter of Blockchain (2024), so kindly mark this issue with appropriate labels (wob, WOB, or wob24) as well as level labels (level1, level2, or level3) so that my contributions can be considered for the program.

**Comment by Harshita9412** [comment]
@Manyap772 Please assign this issue to me under wob'24.

**Comment by ruhilmansi** [comment]
can you please assign me this?

**Comment by AhanaGanguly965** [comment]
@Manyap772 I am very much eager to work on this Can you please assign this to me?

**Comment by Snigdhaaghosh** [comment]
@Manyap772 can you please assign this issue to me under Wob24?
